/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Shape = IDL.Record({
  'id' : IDL.Text,
  'height' : IDL.Nat,
  'borderSize' : IDL.Nat,
  'rotation' : IDL.Opt(IDL.Nat),
  'text' : IDL.Opt(IDL.Text),
  'width' : IDL.Nat,
  'borderColor' : IDL.Text,
  'shapeType' : IDL.Variant({
    'rectangle' : IDL.Null,
    'circle' : IDL.Null,
    'triangle' : IDL.Null,
  }),
  'bgColor' : IDL.Text,
});
export const ThumbnailConfig = IDL.Record({
  'height' : IDL.Nat,
  'borderSize' : IDL.Nat,
  'shapes' : IDL.Vec(Shape),
  'createdAt' : IDL.Int,
  'text' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Opt(IDL.Int),
  'width' : IDL.Nat,
  'borderColor' : IDL.Text,
  'bgColor' : IDL.Text,
});
export const Template = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Opt(IDL.Int),
  'config' : ThumbnailConfig,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTemplate' : IDL.Func([IDL.Text, ThumbnailConfig], [Template], []),
  'deleteTemplate' : IDL.Func([IDL.Text], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTemplate' : IDL.Func([IDL.Text], [Template], ['query']),
  'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Shape = IDL.Record({
    'id' : IDL.Text,
    'height' : IDL.Nat,
    'borderSize' : IDL.Nat,
    'rotation' : IDL.Opt(IDL.Nat),
    'text' : IDL.Opt(IDL.Text),
    'width' : IDL.Nat,
    'borderColor' : IDL.Text,
    'shapeType' : IDL.Variant({
      'rectangle' : IDL.Null,
      'circle' : IDL.Null,
      'triangle' : IDL.Null,
    }),
    'bgColor' : IDL.Text,
  });
  const ThumbnailConfig = IDL.Record({
    'height' : IDL.Nat,
    'borderSize' : IDL.Nat,
    'shapes' : IDL.Vec(Shape),
    'createdAt' : IDL.Int,
    'text' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Opt(IDL.Int),
    'width' : IDL.Nat,
    'borderColor' : IDL.Text,
    'bgColor' : IDL.Text,
  });
  const Template = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Opt(IDL.Int),
    'config' : ThumbnailConfig,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTemplate' : IDL.Func([IDL.Text, ThumbnailConfig], [Template], []),
    'deleteTemplate' : IDL.Func([IDL.Text], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTemplate' : IDL.Func([IDL.Text], [Template], ['query']),
    'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };